language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode

services:
  - mongodb

env:
  - "JRUBY_OPTS=-J-Xmx1024m"

script: bundle exec rake test

notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change

branches:
  only:
    - master
    - develop
